// Generated by CoffeeScript 1.8.0
module.exports = {
  mongoPath: 'mongodb://localhost/reactsample',
  redisSecret: 'foo',
  apipath: 'http://localhost:3000/api',
  username: 'foo',
  password: 'bar'
};
